#!/usr/bin/env ruby
require 'bundler/setup'
require 'mailman'

Mailman.config.logger = Logger.new('log/mailman.log')
Mailman.config.maildir = APP_CONFIG[:maildir]

Mail.defaults do
  delivery_method :smtp, {
    enable_starttls_auto: APP_CONFIG[:starttls]
  }
end

Mailman::Application.run do
  to "%group%@#{APP_CONFIG[:domain]}" do |group_address|
    begin
      group = Group.find_by_address(group_address)

      mail = Mail.new(message)
      mail.to = nil
      mail.bcc = group.emails.pluck('address')
      mail.reply_to = group_address + "@#{APP_CONFIG[:domain]}"

      mail.deliver!
    rescue Exception => e
      Mailman.logger.error "Exception occurred while receiving message:\n#{message}"
      Mailman.logger.error [e, *e.backtrace].join("\n")
    end
  end
end
